baseURL: "https://qcf.ubcquantum.com"
languageCode: "en-ca"
title: UBC QCF 2024 
theme: hugo-bootstrap-5

# Get date from filename, Jekyll-style.
frontmatter:
  date:
    - ":filename"
    - ":default"

permalinks:
  posts: /:section/:year/:month/:day/:slug/
  events: /:section/:year/:month/:day/:slug/

paginate: 5

copyright: © 2024

markup:
  goldmark:
    renderer:
      # Allow HTML inside markdown
      unsafe: true
