[build]
publish = "public"
command = "hugo --minify"

[build.environment]
HUGO_VERSION = "0.121.1"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_ENV = "preview"
